GET http://localhost:8080/secured/status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZUBleGFtcGxlLmNvbSIsIm5iZiI6MTYyNzUxMjgwOSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Im1uamRiY2F1dGgiLCJsYW5ndWFnZSI6ImVuIiwiZXhwIjoxNjI3NTE2NDA5LCJpYXQiOjE2Mjc1MTI4MDksImhhaXJfY29sb3IiOiJicm93biJ9.etKvhx8KNlg1VNxR9aAN3ns20A-cEJu8r-ujKYyb72c