micronaut:
  application:
    name: stockBroker
  server:
    port: 8081
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    endpoints:
      login:
        enabled: true
        path: "/login"
    enabled: true
    authentication: bearer
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: changeThisSecretToALongSecureString
    intercept-url-map:
      - pattern: /swagger-ui/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /swagger/**
        access:
          - isAnonymous()

hello:
  controller:
    path: "/hello"
  service:
    greeting: "Hello from service"
  config:
    greeting:
      de: "Hallo"
      en: "Hello"

#JSON Settings
# TYPE OF PROPERTY NAMES = SNAKE CASE like_that
#jackson:
#  property-naming-strategy: SNAKE_CASE
#  serialization:
#    writeDatesAsTimestamps: false
#    writeDatesWithZoneId: true
#    writeDateTimestampsAsNanoseconds: false
#  generator:
#    writeNumbersAsStrings: true
#    writeBigDecimalAsPlain: true
#  deserialization:
#    failOnUnknownProperties: false
